workspace:
  base: /go
  path: src/github.com/Depado/goploader/

matrix:
  TAG:
    - 1.9
    - 1.8

pipeline:
  # Dep and vendoring
  prerequisites:
    image: golang:${TAG}
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure

  # Test
  test:
    image: golang:${TAG}
    commands:
      - go test ./...