workspace:
  base: /go
  path: src/github.com/Depado/goploader/

pipeline:
  # Dep and vendoring
  prerequisites:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure

  # Test
  test:
    image: golang:1.9
    commands:
      - go test ./...